version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_pizza
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=new_pizza_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: bot_pizza
    env_file: 
      - .env    
    depends_on:
      - postgres

volumes:
  postgres_data: